Models/Lista.cs
namespace PracticaProgramada2_JuanDiegoSanchez.Models
{
    public class Lista
    {
        public int IdLista { get; set; }
        public int IdUsuario { get; set; }
        public required string Nombre { get; set; }
        public required string Descripcion { get; set; }
        public byte[]? Imagen { get; set; }
        public List<Tarea> Tareas { get; set; } = new List<Tarea>();
    }
}

Controllers/ListasController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PracticaProgramada2_JuanDiegoSanchez.AppDbContext;
using PracticaProgramada2_JuanDiegoSanchez.Models;

namespace PracticaProgramada2_JuanDiegoSanchez.Controllers
{
    public class ListasController : Controller
    {
        private readonly ApplicationDbContext _context;


        public ListasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Listas
        public async Task<IActionResult> Index()
        {
            // Este codigo es para dar a entender al programa que para usar las listas, tenemos que estar ingresados con el Usuario que hicimos en el inicio de sesion
            var userId = HttpContext.Session.GetString("UserId");

            if (string.IsNullOrEmpty(userId))
            {
                return RedirectToAction("Login", "Loguear");
            }

            if (!int.TryParse(userId, out int convertir))
            {
                // Esto es por si UserId no funciona
                return BadRequest("UserId no es un número válido.");
            }

            var listas = await _context.Listas.Where(l => l.IdUsuario == convertir).ToListAsync();

            return View(listas);


        }

        // GET: Listas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lista = await _context.Listas
                .FirstOrDefaultAsync(m => m.IdLista == id);
            if (lista == null)
            {
                return NotFound();
            }

            return View(lista);
        }

        // GET: Listas/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdLista,IdUsuario,Nombre,Descripcion,Imagen")] Lista lista)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lista);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(lista);
        }

        // GET: Listas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lista = await _context.Listas.FindAsync(id);
            if (lista == null)
            {
                return NotFound();
            }
            return View(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdLista,IdUsuario,Nombre,Descripcion,Imagen")] Lista lista)
        {
            if (id != lista.IdLista)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lista);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ListaExists(lista.IdLista))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lista);
        }

        // GET: Listas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lista = await _context.Listas
                .FirstOrDefaultAsync(m => m.IdLista == id);
            if (lista == null)
            {
                return NotFound();
            }

            return View(lista);
        }

        // POST: Listas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lista = await _context.Listas.FindAsync(id);
            if (lista != null)
            {
                _context.Listas.Remove(lista);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ListaExists(int id)
        {
            return _context.Listas.Any(e => e.IdLista == id);
        }
    }
}

Views/Listas/Create.cshtml
@model PracticaProgramada2_JuanDiegoSanchez.Models.Lista

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Lista</h4>
<hr />
<div class="row"> 
    <div class="col-md-4">
        <form asp-controller="Listas" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdUsuario" value="@ViewBag.UsuarioId" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" type="file" accept=".jpg,.jpeg,.png" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Listas/Delete.cshtml
@model PracticaProgramada2_JuanDiegoSanchez.Models.Lista

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lista</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdLista" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Listas/Details.cshtml
@model PracticaProgramada2_JuanDiegoSanchez.Models.Lista

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Lista</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsuario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdUsuario)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class="col-sm-10">
            @if (Model.Imagen != null)
            {
                <img src="data:image;base64,@Convert.ToBase64String(Model.Imagen)" alt="Imagen" class="img-thumbnail" />
            }
            else
            {
                <span>No image available</span>
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdLista">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Listas/Edit.cshtml
@model PracticaProgramada2_JuanDiegoSanchez.Models.Lista

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Lista</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdLista" />
            <div class="form-group">
                <label asp-for="IdUsuario" class="control-label"></label>
                <input asp-for="IdUsuario" class="form-control" />
                <span asp-validation-for="IdUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Listas/Index.cshtml
@model IEnumerable<PracticaProgramada2_JuanDiegoSanchez.Models.Lista>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" asp-route-usuarioId="@ViewBag.UsuarioId">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdUsuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdUsuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagen)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdLista">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IdLista">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IdLista">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>